//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayitlar
    {
        public int KayitID { get; set; }
        public int OgrenciID { get; set; }
        public int DersID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
