//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotID { get; set; }
        public int TeslimID { get; set; }
        public Nullable<decimal> FinalPuani { get; set; }
        public Nullable<decimal> SistemOnerilenPuan { get; set; }
        public Nullable<System.DateTime> PuanlamaTarihi { get; set; }
    
        public virtual Teslimler Teslimler { get; set; }
    }
}
