//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odevler()
        {
            this.Teslimlers = new HashSet<Teslimler>();
        }
    
        public int OdevID { get; set; }
        public int DersID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime SonTeslimTarihi { get; set; }
        public Nullable<decimal> Agirlik { get; set; }
        public Nullable<int> ZorlukSeviyesi { get; set; }
        public Nullable<int> TahminiSureDakika { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teslimler> Teslimlers { get; set; }
    }
}
