//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teslimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teslimler()
        {
            this.Notlars = new HashSet<Notlar>();
        }
    
        public int TeslimID { get; set; }
        public int OdevID { get; set; }
        public int OgrenciID { get; set; }
        public string IcerikMetni { get; set; }
        public string DosyaYolu { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string Durum { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlars { get; set; }
        public virtual Odevler Odevler { get; set; }
    }
}
